[wireless]
command=$HOME/.config/i3/blocks/00-wireless.sh
interval=1

[battery]
command=$HOME/.config/i3/blocks/01-battery.sh
interval=60

[volume]
command=$HOME/.config/i3/blocks/02-volume.sh
interval=1
signal=10

[brightness]
command=$HOME/.config/i3/blocks/03-brightness.sh
interval=10
signal=10

[cpu_temperature]
command=$HOME/.config/i3/blocks/04-cputemp.sh
interval=10

[memory]
command=$HOME/.config/i3/blocks/05-memory.sh
interval=10

[disk]
command=$HOME/.config/i3/blocks/06-disk.sh
interval=30

[date]
command=$HOME/.config/i3/blocks/07-date.sh
interval=60

[time]
command=$HOME/.config/i3/blocks/08-time.sh
interval=1
