ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# plugins
zinit ice depth=1; zinit light romkatv/powerlevel10k
zinit light softmoth/zsh-vim-mode
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light MichaelAquilina/zsh-you-should-use
zinit light zsh-users/zsh-history-substring-search

# snippets
zinit snippet OMZL::git.zsh
zinit snippet OMZP::git
zinit snippet OMZP::command-not-found

# load everything
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
autoload -Uz compinit && compinit
zinit cdreplay -q

# turn off sound
unsetopt BEEP

# scripts
fpath+=~/.config/zsh/scripts/

# history
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# completion
zstyle ':completion:*' menu select
zmodload zsh/complist
_comp_options+=(globdots)

# keybindings
zle -N history-substring-search-up
zle -N history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# aliases
alias ls='ls --color'
alias vim='nvim'
alias v='nvim'
alias V='sudo -E nvim'
alias :q='exit'
alias :wq='exit'

alias cfgz='nvim ~/.config/zsh/zshrc'
alias cfgi='nvim ~/.config/i3/config'
alias cfgp='nvim ~/.config/polybar/modules.ini'
alias cfgk='nvim ~/.config/kitty/kitty.conf'
alias cfgn='nvim ~/.config/nvim/init.lua'
alias cfgs='nvim ~/.config/setup.sh'
# alias folder-delete-empty='folder-delete-empty'
# alias folder-extract-recursive='folder-extract-recursive'
