ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# plugins
zinit ice depth=1; zinit light romkatv/powerlevel10k
zinit ice depth=1; zinit light jeffreytse/zsh-vi-mode
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light MichaelAquilina/zsh-you-should-use

# snippets
zinit snippet OMZL::git.zsh
zinit snippet OMZP::git
zinit snippet OMZP::command-not-found

# load everything
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
autoload -Uz compinit && compinit
zinit cdreplay -q

# turn off sound
unsetopt BEEP

# history
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# completion
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Aliases
alias ls='ls --color'
alias vim='nvim'
alias v='nvim'
alias :q='exit'
alias :wq='exit'

alias cfgz='nvim ~/.config/zsh/zshrc'
alias cfgi='nvim ~/.config/i3/config'
alias cfgp='nvim ~/.config/polybar/modules.ini'
alias cfgk='nvim ~/.config/kitty/kitty.conf'
alias cfgn='nvim ~/.config/nvim/init.lua'
alias cfgs='nvim ~/.config/setup.sh'

# keybindings
export KEYTIMEOUT=1
bindkey '^[OA' history-search-backward
bindkey '^[OB' history-search-forward

# extract function
source ~/.config/zsh/extract.zsh
